  CREATE TABLE "BAIRRO" 
   (	"CODB" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40), 
	 PRIMARY KEY ("CODB")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CIDADE" 
   (	"CODCID" NUMBER(*,0) NOT NULL ENABLE, 
	"UF_CODUF" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODCID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CLIENTE" 
   (	"CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(40) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODCLI")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EMAIL" 
   (	"CODEM" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40), 
	"TIPOEMAIL" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODEM")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ENDERECO" 
   (	"CODEN" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"CIDADE_CODCID" NUMBER(*,0) NOT NULL ENABLE, 
	"BAIRRO_CODB" NUMBER(*,0) NOT NULL ENABLE, 
	"LOGRADOURO_CODLOG" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPOLOGRADOURO_CODTL" NUMBER(*,0) NOT NULL ENABLE, 
	"NRO" NUMBER(*,0) NOT NULL ENABLE, 
	"COMPLEMENTO" VARCHAR2(20), 
	"TIPOENDERECO" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODEN")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "FISICA" 
   (	"CPF" VARCHAR2(14) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"RG" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("CPF")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ITEMORCAMENTO" 
   (	"CODIORC" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUTO_SERVICO_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"ORCAMENTO_CODORC" NUMBER(*,0) NOT NULL ENABLE, 
	"QDADE" NUMBER(*,0) NOT NULL ENABLE, 
	"VALOR" FLOAT(126) NOT NULL ENABLE, 
	"APROVADO" CHAR(1) NOT NULL ENABLE, 
	"DESCONTO" FLOAT(126), 
	"ACRESCIMO" FLOAT(126), 
	"VALORAPROV" FLOAT(126), 
	 PRIMARY KEY ("CODIORC")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "JURIDICA" 
   (	"CNPJ" VARCHAR2(18) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"INSCRICAOESTADUAL" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("CNPJ")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "LOGRADOURO" 
   (	"CODLOG" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40), 
	 PRIMARY KEY ("CODLOG")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ORCAMENTO" 
   (	"CODORC" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"DATAORC" DATE NOT NULL ENABLE, 
	"VALOR" FLOAT(126) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODORC")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "OS" 
   (	"CODOS" NUMBER(*,0) NOT NULL ENABLE, 
	"ORCAMENTO_CODORC" NUMBER(*,0) NOT NULL ENABLE, 
	"DATAAPROV" DATE NOT NULL ENABLE, 
	"DATACONCLUSAO" DATE, 
	"VALORAPROV" FLOAT(126) NOT NULL ENABLE, 
	"DESCONTO" FLOAT(126), 
	"ACRESCIMO" FLOAT(126), 
	 PRIMARY KEY ("CODOS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRODUTO_SERVICO" 
   (	"CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(40) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40), 
	"PRECO" FLOAT(126) NOT NULL ENABLE, 
	"DEFINICAO" CHAR(1) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODIGO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TELEFONE" 
   (	"CODTEL" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTE_CODCLI" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(40), 
	"NUMERO" VARCHAR2(14) NOT NULL ENABLE, 
	"TIPOTEL" VARCHAR2(3) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODTEL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TIPOLOGRADOURO" 
   (	"CODTL" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(30), 
	 PRIMARY KEY ("CODTL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UF" 
   (	"CODUF" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(2) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODUF")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CIDADE" ADD FOREIGN KEY ("UF_CODUF")
	  REFERENCES "UF" ("CODUF") ENABLE;

  ALTER TABLE "EMAIL" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;

  ALTER TABLE "ENDERECO" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;
  ALTER TABLE "ENDERECO" ADD FOREIGN KEY ("CIDADE_CODCID")
	  REFERENCES "CIDADE" ("CODCID") ENABLE;
  ALTER TABLE "ENDERECO" ADD FOREIGN KEY ("BAIRRO_CODB")
	  REFERENCES "BAIRRO" ("CODB") ENABLE;
  ALTER TABLE "ENDERECO" ADD FOREIGN KEY ("LOGRADOURO_CODLOG")
	  REFERENCES "LOGRADOURO" ("CODLOG") ENABLE;
  ALTER TABLE "ENDERECO" ADD FOREIGN KEY ("TIPOLOGRADOURO_CODTL")
	  REFERENCES "TIPOLOGRADOURO" ("CODTL") ENABLE;

  ALTER TABLE "FISICA" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;

  ALTER TABLE "ITEMORCAMENTO" ADD FOREIGN KEY ("PRODUTO_SERVICO_CODIGO")
	  REFERENCES "PRODUTO_SERVICO" ("CODIGO") ENABLE;
  ALTER TABLE "ITEMORCAMENTO" ADD FOREIGN KEY ("ORCAMENTO_CODORC")
	  REFERENCES "ORCAMENTO" ("CODORC") ENABLE;

  ALTER TABLE "JURIDICA" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;

  ALTER TABLE "ORCAMENTO" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;

  ALTER TABLE "OS" ADD FOREIGN KEY ("ORCAMENTO_CODORC")
	  REFERENCES "ORCAMENTO" ("CODORC") ENABLE;

  ALTER TABLE "TELEFONE" ADD FOREIGN KEY ("CLIENTE_CODCLI")
	  REFERENCES "CLIENTE" ("CODCLI") ENABLE;